슬롯과 쿨타임입니다
mu29/danbi pull request #11
Opened 2016-10-14 14:45 UTC by jsham0414

커밋 올렸습니다

2016-10-14 15:56 UTC, mu29 requested changes
리뷰 확인해주세요!

2016-10-14 15:56 UTC, mu29 commented on Server/bin/setting.properties
> +Database.database = danbi2
데이터베이스 설정은 기본으로 바꿔서 올려주실 수 있나요?

2016-10-14 15:56 UTC, mu29 commented on Server/src/game/User.java
> +	class CoolTimes
클래스 이름은 복수가 아닌게 좋아요!

2016-10-14 15:56 UTC, mu29 commented on Server/src/packet/Packet.java
> +		packet.put("cooltime2", cooltime2);
`cooltime2` 는 무슨 역할을 하는 변수인가요? 변수명으로 역할을 유추할 수 있게 지어주시면 좋을 것 같아요 :)

2016-10-14 15:56 UTC, mu29 commented on danbi.sql
> +INSERT INTO `setting_skill` VALUES ('1', '크로스 컷', '전사의 기본적인 기술. 적을 두차례 벤다.', '근접 공격', '1', '20', '1', '10', '0', '67', '050-Skill07', 'crossCut');
이거 한글 깨진거 아닌가요? ㅠ_ㅠ

2016-10-14 15:57 UTC, mu29 commented
추가로 스킬에 버그 없는 버전이라고 올리신거 코드 변한게 없는 것 같아요ㅠㅠ

2016-10-15 07:56 UTC, jsham0414 commented
수정하겠습니다 / 두번째로 올린게 클라 내에서 오류가 뜬걸 고친거라 그럴거에요

2016-10-15 08:03 UTC, jsham0414 commented on danbi.sql
> +INSERT INTO `setting_skill` VALUES ('1', '크로스 컷', '전사의 기본적인 기술. 적을 두차례 벤다.', '근접 공격', '1', '20', '1', '10', '0', '67', '050-Skill07', 'crossCut');
앗 아마 저게 오래 켜두면 쿼리 연결이 종료되서 생기는 한글 깨짐 현상이었나...

2016-10-15 09:18 UTC, jsham0414 commented on danbi.sql
> +INSERT INTO `setting_skill` VALUES ('1', '크로스 컷', '전사의 기본적인 기술. 적을 두차례 벤다.', '근접 공격', '1', '20', '1', '10', '0', '67', '050-Skill07', 'crossCut');
아니네요 근데 쿼리 콘솔창에도 utf8이고 세팅도 잘해놨는데 왜 저러지...

2016-10-15 09:23 UTC, mu29 commented on danbi.sql
> +INSERT INTO `setting_skill` VALUES ('1', '크로스 컷', '전사의 기본적인 기술. 적을 두차례 벤다.', '근접 공격', '1', '20', '1', '10', '0', '67', '050-Skill07', 'crossCut');
이거 그대로 import 해도 결과 잘 나오나요?

2016-10-15 09:24 UTC, mu29 commented
테스트 해보신거죠? 해보셨으면 머지할게요!

2016-10-15 09:48 UTC, jsham0414 commented
네 잘 작동합니다

2016-10-15 09:49 UTC, merged